### ISSUE TITLE
How to do path operations?

### ISSUE THREAD

**Issue by natter1** [ansys/pydpf-post#37]
How can I do path operations with DPF-Post results? Like getting displacement along a defined line as is done for pymapdl here:
https://mapdldocs.pyansys.com/examples/00-mapdl-examples/path_operations.html

Is there an example for DPF-Post?

On a more basic level, I'm also unable to get the nodal solution per node. E.g. when using
```
plastic_strain = solution.misc.nodal_accu_eqv_plastic_strain()
field = plastic_strain.get_data_at_field()
```
I guess `field` contains the plastic strain values of the nodes - but there seems to be no corelation to node numbers?

**Comment by akaszynski** [comment]
@rlagha, you can just use scoping to grab the the node numbers, right?

**Comment by rlagha** [comment]
@akaszynski @natter1  yes 
```
field.scoping.ids
field.location #to get the location, Nodal, Elemental, ....
```
I'll share a script allowing to get a path result evaluation,  but you are right in the post module we need to have a helper to get it easily 
Thanks
Ramdane

**Comment by natter1** [comment]
Ok, so for now I used `mapdl.cm` to define `named_selection`'s to define my paths until I learn how to do it with dpf. So with this I can get something like this:

```
solution = post.load_solution(result_path)
accu_plastic_strain_al_line = solution.misc.nodal_accu_eqv_plastic_strain(named_selection="AL_LINE")
field = accu_plastic_strain_al_line.get_data_at_field()
plt.plot(field)
```
But how do I get the xyz-coordinates belonging to these nodes?

**Comment by rlagha** [comment]
Hi @natter1 ,
You can define nodes selection from DPF with 
```
nodes_scoping = dpf.Scoping(ids=[8,9,25], location=dpf.locations.nodal) # the ids are the nodes user numbers, the one that you used to create "AL_LINE" named selection
accu_plastic_strain_al_line = solution.misc.nodal_accu_eqv_plastic_strain(mesh_scoping=nodes_scoping)
```

You can then do:

```
field_data = accu_plastic_strain_al_line.get_data_at_field(0)  #please check that you have only one field, otherwise you need to loop over all the fields
field_scoping= accu_plastic_strain_al_line.get_scoping_at_field(0)
mesh = solution.mesh
mesh_coords = coords = mesh.nodes.coordinates_field
for id in field_scoping:
    coords = mesh_coords.get_entity_data_by_id(id)
    print(coords)
```

**Comment by anslpa** [comment]
Hi, 

Following #45, enhancements in the ansys-dpf-core module (pydpf-core repository) now allow to plot results mapped on a specific PATH of coordinates. More information can be found under PyDPF-Core documentation, in the "Examples/Plotting Examples" section.

Thank you.

**Comment by PProfizi** [comment]
Hi @natter1 @rlagha , following-up on this issue it seems the example provided answers the question.
If OK with all I will be closing this issue.
I think if helpers are needed in PyDPF-Post for these operations, we can open Enhancement Issues with more details in terms of requirements.

**Comment by natter1** [comment]
@PProfizi sorry, right now I'm quite busy, so I could only take a short look at the example. It seems to solve the issue. I think after closing this issue an Enhancement Issue for PyDPF-Post should be opened.

**Comment by PProfizi** [comment]
So before closing this one I'd like to get a clear image of what would be expected as an enhancement. 
A PyDPF-Post helper to query results on a path?
