### ISSUE TITLE
Does pydpf support .res files generated by ansys cfx-solver?

### ISSUE THREAD

**Issue by lyh-source** [ansys/pydpf-post#632]
### Description
I used cfx-solver to get the .res file after the simulation. This can be operated in the cfd-post software, but it is a bit complicated when processing multiple .res files. Does pydpf support the operation of .res files, or is there any way to convert it to other formats?
![Snipaste_2024-04-22_21-21-16](https://github.com/ansys/pydpf-core/assets/73011058/20d3be9d-979f-4a98-93d4-628a2d92e5ec)
This way is not work.
![Snipaste_2024-04-22_21-23-29](https://github.com/ansys/pydpf-core/assets/73011058/9ba16a72-c5d2-40e7-abae-f9c9bbacdef1)

**Comment by PProfizi** [comment]
Hello @lyh-source,
PyDPF does NOT officially support `.res` files from `CFX`. The officially supported formats for `CFX` are `.cas.cff` and `.dat.cff` files.

You can however feed a `.res` file to a `post.FluidSimulation` as both `cas` and `dat` file to get some limited functionalities:

```py
from ansys.dpf import post
from ansys.dpf.post import examples

fluid_example_files = examples.download_cfx_mixing_elbow()
simulation = post.FluidSimulation(
    cas=fluid_example_files["cas"], dat=fluid_example_files["dat"]
)
# Printing the simulation will show most of the available metadata
print(simulation)
```

Again, the `.res` format is not officially supported, meaning that bugs may be present relative to this format and will not get fixed.
To use with caution!
